# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shannon < Formula
  desc "Advanced search and analysis tool for Claude conversation exports"
  homepage "https://github.com/neilberkman/shannon"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilberkman/shannon/releases/download/v0.3.0/shannon_0.3.0_darwin_amd64.tar.gz"
      sha256 "33975d763639b9fe1eb85541b4d6f588d9d6b50997009084c6004a261dffe341"

      define_method(:install) do
        bin.install "shannon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilberkman/shannon/releases/download/v0.3.0/shannon_0.3.0_darwin_arm64.tar.gz"
      sha256 "4d191d9a45d72ac8330fb254a7e47caef6887cecc2d62822b68cbd7c429a9413"

      define_method(:install) do
        bin.install "shannon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/shannon/releases/download/v0.3.0/shannon_0.3.0_linux_amd64.tar.gz"
      sha256 "a9143305a6167e6c13da7eacdb92838073c7c2f3fd411750ff2ae00381c3515b"
      define_method(:install) do
        bin.install "shannon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/shannon/releases/download/v0.3.0/shannon_0.3.0_linux_arm64.tar.gz"
      sha256 "cc25c25947826275e6ef6b136be4524c74fa2501dd76e639938165bb0bae4097"
      define_method(:install) do
        bin.install "shannon"
      end
    end
  end

  test do
    system "#{bin}/shannon", "--version"
  end
end
